name: Release Desktop

on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  release:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./desktop
        
    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT
        
    - name: Get Release Notes
      id: release_notes
      shell: bash
      run: |
        RELEASE_NOTES=$(cat RELEASES_NOTES.md)
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "installer/BuanaVPad-Setup.exe"
        body: |
          Published at ${{ steps.date.outputs.date }}
          
          ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        name: "BuanaVPad ${{ github.ref_name }}"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ github.ref_name }}