name: Release Desktop

on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./desktop
    
    steps:
    - uses: actions/checkout@v4

    - name: Install wheels
      shell: cmd
      run: |
        call wheels\Scripts\activate.bat
        pip install pyinstaller
        pyinstaller --clean buanavpad.spec
    
    - name: Download and Install Inno Setup
      shell: pwsh
      run: |
        $installerUrl = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
        Invoke-WebRequest -Uri $installerUrl -OutFile "innosetup.exe"
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
    
    - name: Build Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT
        
    - name: Get Release Notes
      id: release_notes
      shell: bash
      run: |
        RELEASE_NOTES=$(cat RELEASES_NOTES.md)
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "installer/BuanaVPad-Setup.exe"
        body: |
          Published at ${{ steps.date.outputs.date }}
          
          ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        name: "BuanaVPad ${{ github.ref_name }}"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ github.ref_name }}
    
    - name: Upload Debug Info on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info
        path: |
          desktop/
          !desktop/env/
          !desktop/**/__pycache__